-- CONTROL DE TRABAJO V19.0
-- Ejecutar una sola vez en Supabase SQL Editor.
create table if not exists public.jornadas_trabajo (
 id bigint generated by default as identity primary key,
 fecha date not null,
 hora_inicio time not null,
 hora_fin time,
 km_inicio numeric(12,1) not null,
 km_final numeric(12,1),
 km_recorridos numeric(12,1),
 horas_trabajadas numeric(8,2),
 horas_planificadas numeric(8,2) not null,
 viajes integer not null default 0,
 meta_dia numeric(12,0) not null default 0,
 combustible numeric(12,0),
 mantenimiento numeric(12,0),
 ganancia_bruta numeric(12,0),
 comision_app numeric(12,0),
 ganancia_neta numeric(12,0),
 notas text,
 estado text not null default 'en_curso' check (estado in ('en_curso','cerrada')),
 plan_horas_meta numeric(8,2), plan_viajes integer, plan_km numeric(12,1),
 plan_combustible numeric(12,0), plan_mantenimiento numeric(12,0),
 plan_ganancia_bruta numeric(12,0), plan_ganancia_neta numeric(12,0),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.jornadas_trabajo alter column hora_fin drop not null;
alter table public.jornadas_trabajo alter column km_final drop not null;
alter table public.jornadas_trabajo alter column horas_trabajadas drop not null;
alter table public.jornadas_trabajo alter column km_recorridos drop not null;
alter table public.jornadas_trabajo alter column combustible drop not null;
alter table public.jornadas_trabajo alter column mantenimiento drop not null;
alter table public.jornadas_trabajo alter column ganancia_bruta drop not null;
alter table public.jornadas_trabajo alter column comision_app drop not null;
alter table public.jornadas_trabajo alter column ganancia_neta drop not null;
create index if not exists jornadas_trabajo_fecha_idx on public.jornadas_trabajo(fecha desc);
create index if not exists jornadas_trabajo_estado_idx on public.jornadas_trabajo(estado);
alter table public.jornadas_trabajo enable row level security;
drop policy if exists jornadas_read on public.jornadas_trabajo;
drop policy if exists jornadas_insert on public.jornadas_trabajo;
drop policy if exists jornadas_update on public.jornadas_trabajo;
drop policy if exists jornadas_delete on public.jornadas_trabajo;
create policy jornadas_read on public.jornadas_trabajo for select to anon, authenticated using (true);
create policy jornadas_insert on public.jornadas_trabajo for insert to anon, authenticated with check (true);
create policy jornadas_update on public.jornadas_trabajo for update to anon, authenticated using (true) with check (true);
create policy jornadas_delete on public.jornadas_trabajo for delete to anon, authenticated using (true);
